# Automatically generated by configure - do not modify
SRC_PATH=/home/temkink/openxt/builds/qemu14/build/tmp-eglibc/work/core2-oe-linux/qemu-dm-1.4.0-r0/qemu-1.4.0/roms/seabios
AS=i586-oe-linux-as
CC=i586-oe-linux-gcc  -m32    -march=core2 -msse3 -mtune=generic -mfpmath=sse --sysroot=/home/temkink/openxt/builds/qemu14/build/tmp-eglibc/sysroots/xenclient-dom0
BCC=bcc
CPP=i586-oe-linux-gcc -E --sysroot=/home/temkink/openxt/builds/qemu14/build/tmp-eglibc/sysroots/xenclient-dom0  -m32    -march=core2 -msse3 -mtune=generic -mfpmath=sse
OBJCOPY=objcopy
IASL=iasl
LD=i586-oe-linux-ld --sysroot=/home/temkink/openxt/builds/qemu14/build/tmp-eglibc/sysroots/xenclient-dom0
